Repository owncloud/encryption, pull requests merged in 2018-12, with the labels that each got.

#77 Run cli acceptance tests for pgsql and PHP 7.2
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#82 Use unique usernames in unit tests
  tests/unit/Crypto/DecryptAllTest.php
  tests/unit/Crypto/EncryptAllTest.php
Labels: 3 - To Review

#84 use bootstrap.php of core acceptance tests
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#85 Run all 15 parts of core webUI test suites
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#86 Adjust 'make help' output
  Makefile
Labels: 4 - To release, QA-team

#87 Refactor running core acceptance tests
  .drone.yml
  Makefile
Labels: 3 - To Review, QA-team, dev:acceptance-tests
