Repository owncloud/encryption, pull requests merged in 2018-11, with the labels that each got.

#66 Add skip on failing test and add web ui suite on drone
  .drone.yml
  tests/acceptance/features/bootstrap/WebUIPersonalEncryptionSettingsContext.php
  tests/acceptance/features/lib/AdminEncryptionSettingsPage.php
  tests/acceptance/features/webUIUserKeysType/userKeys.feature
Labels: 3 - To Review, QA-team

#28 [phpunit] Fail on warnings
  tests/Crypto/EncryptAllTest.php
  tests/phpunit.xml
Labels: 3 - To Review

#69 Adjust acceptance test step text similar to core
  tests/acceptance/features/bootstrap/WebUIAdminEncryptionSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalEncryptionSettingsContext.php
  tests/acceptance/features/webUIUserKeysType/userKeys.feature
Labels: 4 - To release, QA-team

#68 Add more tests to drone
  .drone.yml
Labels: 3 - To Review, QA-team

#73 Adjust acceptance test step text changed in core
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/acceptance/features/cliEncryption/recreatemasterkey.feature
  tests/acceptance/features/webUIUserKeysType/userKeys.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#71 Remove travis as tests are now in drone
  .drone.yml
  .travis.yml
Labels: 3 - To Review, QA-team
