Repository owncloud/encryption, pull requests merged in 2019-02, with the labels that each got.

#22 skip shared files when adding recovery key
  lib/Recovery.php
  tests/unit/RecoveryTest.php
Labels: 4 - To release, backport-request, bug

#90 Integrate HSM changes to encryption
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Command/HSMDaemon.php
  lib/Crypto/Crypt.php
  lib/Crypto/CryptHSM.php
  lib/Hooks/UserHooks.php
  lib/JWT.php
  lib/KeyManager.php
  lib/Recovery.php
  lib/Users/Setup.php
  tests/unit/Command/HSMDaemonTest.php
  tests/unit/Crypto/CryptHSMTest.php
  tests/unit/JWTTest.php
Labels: 3 - To Review

#96 Unskip test for issue-33
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/acceptance/features/webUIUserKeysType/userKeys.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#104 do not trim content of downloaded file
  tests/acceptance/features/bootstrap/EncryptionContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#21 Add re-login information after successful action
  lib/Command/RecreateMasterKey.php
  tests/unit/Command/RecreateMasterKeyTest.php
Labels: 3 - To Review, backport-request
