Repository owncloud/encryption, pull requests merged in 2019-04, with the labels that each got.

#112 Php unit 5 to 6
  composer.lock
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/unit/Command/HSMDaemonTest.php
  tests/unit/Command/RecreateMasterKeyTest.php
  tests/unit/Command/TestEnableMasterKey.php
  tests/unit/Command/TestEnableUserKey.php
  tests/unit/Controller/RecoveryControllerTest.php
  tests/unit/Controller/SettingsControllerTest.php
  tests/unit/Controller/StatusControllerTest.php
  tests/unit/Crypto/CryptHSMTest.php
  tests/unit/Crypto/CryptTest.php
  tests/unit/Crypto/DecryptAllTest.php
  tests/unit/Crypto/EncryptAllTest.php
  tests/unit/Crypto/EncryptionTest.php
  tests/unit/Hooks/UserHooksTest.php
  tests/unit/JWTTest.php
  tests/unit/KeyManagerTest.php
  tests/unit/MigrationTest.php
  tests/unit/RecoveryTest.php
  tests/unit/SessionTest.php
  tests/unit/Users/SetupTest.php
  tests/unit/UtilTest.php
Labels: 3 - To Review, QA-team

#114 Enable failOnRisky for phpunit tests
  phpunit.xml
  tests/unit/Hooks/UserHooksTest.php
Labels: 4 - To release, QA-team

#115 Add encryption version fix command
  appinfo/info.xml
  lib/Command/FixEncryptedVersion.php
  tests/unit/Command/FixEncryptedVersionTest.php
  tests/unit/Hooks/UserHooksTest.php
Labels: 3 - To Review

#116 Fix minor typo in FixEncryptedVersionTest
  tests/unit/Command/FixEncryptedVersionTest.php
Labels: 3 - To Review

#119 Remove unused use statements
  lib/Command/FixEncryptedVersion.php
  lib/Command/HSMDaemon.php
  lib/Command/RecreateMasterKey.php
  lib/Crypto/DecryptAll.php
  lib/KeyManager.php
  tests/unit/Command/FixEncryptedVersionTest.php
  tests/unit/Command/RecreateMasterKeyTest.php
  tests/unit/Crypto/DecryptAllTest.php
  tests/unit/Crypto/EncryptAllTest.php
Labels: 3 - To Review

#117 Fix minor wording corrections in command
  .phan/config.php
  appinfo/Migrations/Version20170913113840.php
  appinfo/app.php
  appinfo/routes.php
  css/settings-admin.css
  lib/AppInfo/Application.php
  lib/Command/FixEncryptedVersion.php
  lib/Command/HSMDaemon.php
  lib/Command/MigrateKeys.php
  lib/Command/RecreateMasterKey.php
  lib/Command/SelectEncryptionType.php
  lib/Controller/RecoveryController.php
  lib/Controller/SettingsController.php
  lib/Controller/StatusController.php
  lib/Crypto/Crypt.php
  lib/Crypto/CryptHSM.php
  lib/Crypto/DecryptAll.php
  lib/Crypto/EncryptAll.php
  lib/Crypto/Encryption.php
  lib/Exceptions/MultiKeyDecryptException.php
  lib/Exceptions/MultiKeyEncryptException.php
  lib/Exceptions/PrivateKeyMissingException.php
  lib/Exceptions/PublicKeyMissingException.php
  lib/HookManager.php
  lib/Hooks/Contracts/IHook.php
  lib/Hooks/UserHooks.php
  lib/JWT.php
  lib/KeyManager.php
  lib/Migration.php
  lib/Panels/Admin.php
  lib/Panels/Personal.php
  lib/Recovery.php
  lib/Session.php
  lib/Users/Setup.php
  lib/Util.php
  tests/unit/Command/FixEncryptedVersionTest.php
  tests/unit/Command/RecreateMasterKeyTest.php
  tests/unit/Command/TestEnableMasterKey.php
  tests/unit/Command/TestEnableUserKey.php
  tests/unit/Controller/RecoveryControllerTest.php
  tests/unit/Controller/SettingsControllerTest.php
  tests/unit/Controller/StatusControllerTest.php
  tests/unit/Crypto/CryptTest.php
  tests/unit/Crypto/DecryptAllTest.php
  tests/unit/Crypto/EncryptAllTest.php
  tests/unit/Crypto/EncryptionTest.php
  tests/unit/HookManagerTest.php
  tests/unit/Hooks/UserHooksTest.php
  tests/unit/KeyManagerTest.php
  tests/unit/MigrationTest.php
  tests/unit/Panels/AdminTest.php
  tests/unit/Panels/PersonalTest.php
  tests/unit/RecoveryTest.php
  tests/unit/SessionTest.php
  tests/unit/Users/SetupTest.php
  tests/unit/UtilTest.php
  tests/unit/bootstrap.php
Labels: 4 - To release

#120 Fixing encrypted version test
  tests/unit/Command/FixEncryptedVersionTest.php
Labels: 3 - To Review, backport-request
