Repository owncloud/encryption, pull requests merged in 2019-05, with the labels that each got.

#121 improve CI
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#127 do not disable encryption app after test run
  tests/unit/Command/FixEncryptedVersionTest.php
Labels: 3 - To Review, QA-team

#124 Add acceptance test for checking file access after recreating master key in encryption
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/webUIMasterKeyType/webUIMasterKeys.feature
Labels: 3 - To Review, QA-team, backport-request, dev:acceptance-tests

#128 Fix recreate masterkey for hsm
  lib/Command/RecreateMasterKey.php
  lib/Crypto/EncryptAll.php
  lib/Factory/EncDecAllFactory.php
  lib/Util.php
  tests/unit/Command/RecreateMasterKeyTest.php
  tests/unit/Crypto/EncryptAllTest.php
  tests/unit/Factory/EncDecAllFactoryTest.php
  tests/unit/UtilTest.php
Labels: 3 - To Review
