Repository owncloud/encryption, pull requests merged in 2020-12, with the labels that each got.

#218 add path option to FixEncryptedVersion command
  lib/Command/FixEncryptedVersion.php
  tests/unit/Command/FixEncryptedVersionTest.php
Labels: 3 - To Review

#219 [Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud
  .drone.star
  .gitignore
  sonar-project.properties
Labels: 4 - To release, QA-team

#221 [Tests-Only][CI] fix sonarcloud reporting in CI
  .drone.star
  sonar-project.properties
Labels: QA-team

#226 Prevent command encryption:fix-encrypted-version from printing file binary data
  lib/Command/FixEncryptedVersion.php
  tests/unit/Command/FixEncryptedVersionTest.php
Labels: 3 - To Review

#227 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.star
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To Review, QA-team
