Repository owncloud/encryption, pull requests merged in 2021-05, with the labels that each got.

#265 [tests-only] Adjust accceptance test matrix
  .drone.starlark
  .drone.yml
Labels: QA-team

#267 [tests-only] Use .drone.star directly in CI
  .drone.star
  .drone.yml
  Makefile
Labels: QA-team

#268 [tests-only] Bump phan analysis to v4.0
  .phan/config.php
  vendor-bin/phan/composer.json
Labels: QA-team

#261 Use binary encoding setting for HSM
  CHANGELOG.md
  lib/Crypto/CryptHSM.php
Labels: 3 - To Review

#273 Restore encrypted version to original if no fix was found
  CHANGELOG.md
  lib/Command/FixEncryptedVersion.php
  tests/unit/Command/FixEncryptedVersionTest.php
Labels: bug

#272 determine encryption format from length
  lib/Crypto/CryptHSM.php
Labels: 3 - To Review
