Repository owncloud/encryption, pull requests merged in 2021-01, with the labels that each got.

#222 Fix the hsm decrypt command
  appinfo/info.xml
  lib/Command/HSMDaemon.php
  lib/Command/HSMDaemonDecrypt.php
  tests/unit/Command/HSMDaemonDecryptTest.php
  tests/unit/Command/HSMDaemonTest.php
Labels: 3 - To Review

#25 Replacing old hooks with symfony events
  lib/AppInfo/Application.php
  lib/Hooks/UserHooks.php
  tests/unit/Command/FixEncryptedVersionTest.php
  tests/unit/Hooks/UserHooksTest.php
Labels: 3 - To Review

#231 [tests-only] Pin behat/gherkin because of Gherkin issue 187
  lib/Crypto/Crypt.php
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team

#230 [docs-only] SonarCloud badges
  .gitignore
  README.md
Labels: 4 - To release, QA-team

#234 [tests-only] Bump behat/gherkin to 4.7.1
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team
